version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: crud_mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: crud
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: crud_phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "8081:80"
        depends_on:
            - mysql

volumes:
    mysql_data:
